### ISSUE TITLE
Using template on .NET Core 3.x

### ISSUE THREAD

**Issue by maxild** [giraffe-fsharp/giraffe-template#32]
Hi,

I just started using Giraffe, and scaffolded using 

```
dotnet new giraffe -o GiraffeWebUI -lang F# -I -U
``` 

Here are some changes I made, because I wanted to run on .NET Core 3.x (not all are needed)

1. I changed to using paket as a local tool (not needed, but better to run paket on core everywhere)
2. build.[bat|sh] should be updated to use `dotnet tool restore` and `dotnet paket install/restore(?)` for bootstrapping using local tool. Same goes for readme, I guess.
3. Inserted `nuget FSharp.Core 4.7.0` in dependencies.paket
4. Removed `nuget Microsoft.AspNetCore.App` in dependencies.paket (shared framework in 3.x)
5. Changed TFM from netcoreapp2.1 to netcoreapp3.1 in fsproj files
6. Added `open Microsoft.Extensions.Hosting` in program.fs, after having changed to using `IWebHostEnvironment` in configureApp

Sorry for opening all these in single issue. Maybe not all people are on netcoreapp3.x (I doubt it when we are talking `dotnet new` for giraffe-beginners like myself). Anyway this is just a heads up. Nothing important :wink:

Maybe I forgot something.

Looking forward to using F# on aspnetcore.

**Comment by dburriss** [comment]
@dustinmoris can I submit a PR for updating the template with the minimal amount of changes to upgrade project and test project to 3.1?

**Comment by dustinmoris** [comment]
@dburriss Sure, that would be much appreciated!

**Comment by dburriss** [comment]
A quick update on 2 points.
1. Currently, I have all tests passing except for Razor project.
> System.Exception : "Method not found: 'System.Collections.Generic.IList`1<Microsoft.Extensions.FileProviders.IFileProvider> Microsoft.AspNetCore.Mvc.Razor.RazorViewEngineOptions.get_FileProviders()'."

I found [this](https://docs.microsoft.com/en-us/dotnet/core/compatibility/2.2-3.1#razor-runtime-compilation-moved-to-a-package) change which is the likely cause.

2. I wanted to propose a change.

``` fsharp
(match env.EnvironmentName with
    | "Development"  -> app.UseDeveloperExceptionPage()
    | _ -> app.UseGiraffeErrorHandler errorHandler)
```
This uses `.EnvironmentName` and matches on a `string` rather than `IsDevelopment()`. That extension now requires an extra package since `IHostingEnvironment` is deprecated and I am making a change to `IWebHostEnvironment`.
The string is more transparent to what is going on and doesn't require an extra package. Someone can always change it in their project if they prefer magic. Thoughts @dustinmoris  ?

**Comment by dustinmoris** [comment]
@dburriss Maybe take a look at this PR where @JonCanning upgraded the Razor project to .NET Core 3.1: https://github.com/giraffe-fsharp/Giraffe.Razor/pull/14/files

> This uses .EnvironmentName and matches on a string rather than IsDevelopment(). That extension now requires an extra package since IHostingEnvironment is deprecated and I am making a change to IWebHostEnvironment.
The string is more transparent to what is going on and doesn't require an extra package. Someone can always change it in their project if they prefer magic.

Sounds reasonable to me!

**Comment by dburriss** [comment]
@dustinmoris yes using the middleware from Jon's PR works.
Not sure how you would prefer to proceed here though?

1. Wait for PR 14 to get merged
1. Copy the middleware into the project, pin the Giraffe.Razor version, and then remove the file and unpin after it is merged
1. Leave only the Razor template on netcoreapp2.1

I can review the PR more and pull down and test on netcore 2 & 3 if that will help move things along since I already went through it to figure out what I needed?

**Comment by sethlivingston** [comment]
This is the main I ended up with to get things running properly both locally and on an Azure App Service:

```fsharp
[<EntryPoint>]
let main args =
    let contentRoot = Directory.GetCurrentDirectory()
    let webRoot = Path.Combine(contentRoot, "WebRoot")
    Host.CreateDefaultBuilder(args)
        .ConfigureWebHostDefaults(fun webBuilder -> 
            webBuilder
                .UseKestrel()
                .UseContentRoot(contentRoot)
                .UseIIS()
                .UseWebRoot(webRoot)
                .Configure(Action<IApplicationBuilder> configureApp)
                .ConfigureServices(configureServices)
                .ConfigureLogging(configureLogging)
            |> ignore
        ) 
        .Build()
        .Run()
    0
```

The README for the main Giraffe repo uses a similar approach. 

I'm just posting here in case it's useful. Thank you for all of your hard work.

**Comment by dustinmoris** [comment]
All templates have been updates to `netcoreapp3.1` and received many more improvements. Please check the latest `README.md` updates with the new changes and the release notes of the `1.0.0` release: https://www.nuget.org/packages/giraffe-template/1.0.0
